"""阅读端服务层：账号、选源、聚合搜索、书架、进度、章节缓存、订阅源。

和 `engine/` 的分工：`engine/` 是纯求值、不碰 IO 也不碰 DB；`reader/` 负责把它
接到真实的归档文件、网络和数据库上。所以**这一层可以** import requests /
sqlalchemy / funread.legado.manage，`engine/` 不行。
"""

from .matching import ChapterMatch, match_chapter, match_chapter_in, normalize_chapter_name
from .registry import SourceRegistry
from .rss_service import KIND_FEED, KIND_LEGADO, RssService
from .service import (
    DEFAULT_SEARCH_SOURCES,
    DEFAULT_SEARCH_WORKERS,
    AggregatedBook,
    ReaderService,
)
from .storage import (
    LOCAL_USER_ID,
    ReaderChapterCache,
    ReaderProgress,
    ReaderRssArticleState,
    ReaderRssSubscription,
    ReaderShelfBook,
    ReaderSourcePref,
    claim_local_data,
    clear_chapter_cache,
    compute_article_key,
    compute_book_key,
    compute_sub_id,
    count_read,
    get_article_states,
    get_cached_chapter,
    get_progress,
    get_shelf_book,
    get_subscription,
    init_reader_db,
    list_cached_chapter_indexes,
    list_favorites,
    list_shelf,
    list_source_prefs,
    list_subscriptions,
    mark_all_read,
    record_source_result,
    record_subscription_fetch,
    remove_shelf_book,
    remove_subscription,
    save_cached_chapter,
    save_progress,
    set_article_state,
    upsert_shelf_book,
    upsert_source_prefs,
    upsert_subscription,
)

__all__ = [
    "AggregatedBook",
    "ChapterMatch",
    "DEFAULT_SEARCH_SOURCES",
    "DEFAULT_SEARCH_WORKERS",
    "KIND_FEED",
    "KIND_LEGADO",
    "LOCAL_USER_ID",
    "ReaderChapterCache",
    "ReaderProgress",
    "ReaderRssArticleState",
    "ReaderRssSubscription",
    "ReaderService",
    "ReaderShelfBook",
    "ReaderSourcePref",
    "RssService",
    "SourceRegistry",
    "claim_local_data",
    "clear_chapter_cache",
    "compute_article_key",
    "compute_book_key",
    "compute_sub_id",
    "count_read",
    "get_article_states",
    "get_cached_chapter",
    "get_progress",
    "get_shelf_book",
    "get_subscription",
    "init_reader_db",
    "list_cached_chapter_indexes",
    "list_favorites",
    "list_shelf",
    "list_source_prefs",
    "list_subscriptions",
    "mark_all_read",
    "match_chapter",
    "match_chapter_in",
    "normalize_chapter_name",
    "record_source_result",
    "record_subscription_fetch",
    "remove_shelf_book",
    "remove_subscription",
    "save_cached_chapter",
    "save_progress",
    "set_article_state",
    "upsert_shelf_book",
    "upsert_source_prefs",
    "upsert_subscription",
]
