"""阅读端服务层：账号、选源、聚合搜索、书架、进度、章节缓存、订阅源。

和 `engine/` 的分工：`engine/` 是纯求值、不碰 IO 也不碰 DB；`reader/` 负责把它
接到真实的归档文件、网络和数据库上。所以**这一层可以** import requests /
sqlalchemy / funread.legado.manage，`engine/` 不行。
"""

from .registry import SourceRegistry
from .rss_service import KIND_FEED, KIND_LEGADO, RssService
from .service import (
    DEFAULT_SEARCH_SOURCES,
    DEFAULT_SEARCH_WORKERS,
    AggregatedBook,
    ReaderService,
)
from .storage import (
    LOCAL_USER_ID,
    MIN_PASSWORD_LENGTH,
    USERNAME_PATTERN,
    ReaderChapterCache,
    ReaderProgress,
    ReaderRssArticleState,
    ReaderRssSubscription,
    ReaderShelfBook,
    ReaderSourcePref,
    ReaderUser,
    authenticate,
    claim_local_data,
    clear_chapter_cache,
    compute_article_key,
    compute_book_key,
    compute_sub_id,
    count_read,
    count_users,
    create_user,
    get_article_states,
    get_cached_chapter,
    get_progress,
    get_shelf_book,
    get_subscription,
    get_user,
    get_user_by_name,
    hash_password,
    init_reader_db,
    list_cached_chapter_indexes,
    list_favorites,
    list_shelf,
    list_source_prefs,
    list_subscriptions,
    mark_all_read,
    record_source_result,
    record_subscription_fetch,
    remove_shelf_book,
    remove_subscription,
    save_cached_chapter,
    save_progress,
    set_article_state,
    upsert_shelf_book,
    upsert_source_prefs,
    upsert_subscription,
    verify_password,
)

__all__ = [
    "AggregatedBook",
    "DEFAULT_SEARCH_SOURCES",
    "DEFAULT_SEARCH_WORKERS",
    "KIND_FEED",
    "KIND_LEGADO",
    "LOCAL_USER_ID",
    "MIN_PASSWORD_LENGTH",
    "ReaderChapterCache",
    "ReaderProgress",
    "ReaderRssArticleState",
    "ReaderRssSubscription",
    "ReaderService",
    "ReaderShelfBook",
    "ReaderSourcePref",
    "ReaderUser",
    "RssService",
    "SourceRegistry",
    "USERNAME_PATTERN",
    "authenticate",
    "claim_local_data",
    "clear_chapter_cache",
    "compute_article_key",
    "compute_book_key",
    "compute_sub_id",
    "count_read",
    "count_users",
    "create_user",
    "get_article_states",
    "get_cached_chapter",
    "get_progress",
    "get_shelf_book",
    "get_subscription",
    "get_user",
    "get_user_by_name",
    "hash_password",
    "init_reader_db",
    "list_cached_chapter_indexes",
    "list_favorites",
    "list_shelf",
    "list_source_prefs",
    "list_subscriptions",
    "mark_all_read",
    "record_source_result",
    "record_subscription_fetch",
    "remove_shelf_book",
    "remove_subscription",
    "save_cached_chapter",
    "save_progress",
    "set_article_state",
    "upsert_shelf_book",
    "upsert_source_prefs",
    "upsert_subscription",
    "verify_password",
]
